import { Inter } from "next/font/google";
import "./globals.css";
import "./styles/nav.css";
import "./styles/banner.css";
import "./styles/about.css";
import "./styles/portfolio.css";
import "./styles/skills.css";
import "./styles/testimonial.css";
import "./styles/insights.css";
import "./styles/newsletter.css";
import "./styles/footer.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
