import { Inter } from "next/font/google";
import "./globals.css";
import "animate.css";
import AOSProvider from "./components/AOSProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Israel Nwangwu",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AOSProvider>{children}</AOSProvider>
      </body>
    </html>
  );
}
